# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filebrowser < Formula
  desc "File Browser is a create-your-own-cloud-kind of software where you can install it on a server, direct it to a path and then access your files through a nice web interface"
  homepage "https://filebrowser.org"
  version "2.16.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/filebrowser/filebrowser/releases/download/v2.16.0/darwin-amd64-filebrowser.tar.gz"
      sha256 "9f8b1e38b0ec4b99ba34723af5e6b92a7da70fd6de4293a5faf273332bbcda2e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/filebrowser/filebrowser/releases/download/v2.16.0/darwin-arm64-filebrowser.tar.gz"
      sha256 "8927fb91fcccc14bdddb3df4915076d67555517117de8f309a8fbc7420b4d281"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/filebrowser/filebrowser/releases/download/v2.16.0/linux-amd64-filebrowser.tar.gz"
      sha256 "b03baa982693dc8f12f1d21ceb4773071ff754437fa9f618dcec5afc4355c672"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/filebrowser/filebrowser/releases/download/v2.16.0/linux-armv6-filebrowser.tar.gz"
      sha256 "aff3cd44781423e6ab419ec427e4b0dcec40849707384d8b11f340cadbd908b8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/filebrowser/filebrowser/releases/download/v2.16.0/linux-arm64-filebrowser.tar.gz"
      sha256 "a64d0ffc1008a3679066270ebd45737d19db43bb9c3823dff52b7c058ecc44be"
    end
  end

  def install
    bin.install "filebrowser"
  end
end
